# All the sensor measurements needed to perform movement control are found here.
# The topic name for this is "mov_measures".
# TODO: Add the units I want these to have as comments

float32 z  # Depth/heave measurement
float32 vel_x  # Velocity in x-direction
float32 vel_y  # Velocity in y-direction
float32 vel_z  # Velocity in z-direction
float32 qx  # Quaternion x value
float32 qy  # Quaternion y value
float32 qz  # Quaternion z value
float32 qw  # Quaternion w value
float32 yaw
float32 pitch
float32 roll
