#This are the movements and activation commands that need to be requested
# The name of the service is "mov_ctrl_req"

# Commands that can be performed with controllers
 bool   switch
 bool   activate
 bool   deactivate

 # All the "controllers" for movement control
 bool   forward
 bool   right
 bool   depth
 bool   yaw
 bool   pitch
 bool   roll
---
 bool   req_status
 # The one above if the request was processed or not
